#!/usr/bin/python3.10

# Currently, this script will take in files and spit them out, but if it's a webp, it'll
# check if it's animated or not, then convert it to either jpeg or gif, depending.
#It should also do something similar with HEIC, but I don't remember if I got that working
#or if I just gave up and left the code there. Oh well. It's a work in progress.
#The goal is to eventually have it process all kinds of media for storage.
#Until webp is better supported, I'll still be doing this.
#It also has a progress bar.

import os
from PIL import Image
from progress.bar import IncrementalBar
from pillow_heif import register_heif_opener

register_heif_opener()

list = os.listdir(os.getcwd())
#print (list)
bar = IncrementalBar('Processing:', max=len(list))
for each in list:
	bar.next()
	if each.lower().endswith('.gif'):
		img = Image.open(each)
		iffi = getattr(img, "is_animated", False)
		if iffi:
			#print ('animated gif')
			pass
		else:
			#print ('gif')
			pass
		img.close()
	elif each.lower().endswith('.webp'):
		#print (each)
		img = Image.open(each)
		iffi = getattr(img, "is_animated", False)
		if iffi:
			#print ('animated webp')
			img.info.pop('background', None)
			img.save(each.replace(".webp",".gif"), 'gif', save_all=True)
		else:
			#print('webp')
			img.save(each.replace(".webp",".jpg"), 'jpeg')
	elif each.lower().endswith('.heic'):
		img = Image.open(each)
		iffi = getattr(img, "is_animated", False)
		if iffi:
			#print ('animated HEIF')
			img.info.pop('background', None)
			img.save(each.lower().replace(".heic",".gif"), 'gif', save_all=True)
		else:
			#print ("heic still")
			img.save(each.replace(".heic",".png"), 'png', save_all=True)
	else:
		pass
		#print ('neither')	
bar.finish()

