#!/bin/bash

#make a text file with each stream in a new lne
#if i didnt include series prompt there is risk you could overwrite
#files you previously downloaded

COUNTER=1

echo "series:"
read series
for x in *.txt
do
	while read -r line;
	do
		ffmpeg -i "$line" -codec copy "/Cortana/Downloads-S/M3U8s/${series}_${COUNTER}.mp4" &
		((COUNTER=COUNTER+1))
	done < "$x"
done
