#!/bin/bash

COUNTER=1
re="name=(.*)"
prefix="name="

function ProgressBar {
    let _progress=(${1}*100/${2}*100)/100
    let _done=(${_progress}*4)/10
    let _left=40-$_done
    _done=$(printf "%${_done}s")
    _left=$(printf "%${_left}s")
    printf "\rProgress : [${_done// /#}${_left// /-}] ${_progress}%%"; }

#echo "series:"
#read series

totes=$(wc -l < /path/to/list.txt) 
for x in /path/to/list.txt
do
    while read -r line;
    do
        ProgressBar ${COUNTER} ${totes}
        if [[ $line =~ $re ]]; 
        then
            title=${BASH_REMATCH#"$prefix"};
        else
            sleep 1;
        fi
        sudo docker run --rm -v /path/to/downloads:/down -w /down --network=container:Gluetun_S jrottenberg/ffmpeg -hide_banner -loglevel error -i "$line" -codec copy "$title";
        ((COUNTER=COUNTER+1));
    done < "$x"
done
echo \n
