#!/bin/bash

# This script can be dangerous because it'll delete your archives
# after it runs. However, I sometimes need it to do that when I'm working
# in limited space.

for i in *.zip
do
	unzip "$i"
	rm -rf "$i"
done
for i in *.rar
do
	unrar x "$i" 
	rm -rf "$i"
done
